#!/bin/env python3

import os
import sys
import subprocess

SCRIPT_PATH = os.path.dirname(os.path.realpath(__file__))
OUTPUT_PNG = "renderer_old.png"
FAIL_PNG = "renderer_new" # .png added by test
DIFF_PNG = "renderer_diff.png"
BIN_DIR = "./bin"
INKSCAPE_BIN = os.path.join(BIN_DIR, "inkscape")
PATCH_BIN = os.path.join(BIN_DIR, "renderer-drawing-tests-render-png-output")

def main():
    if len(sys.argv) < 2:
        raise ValueError("Please call with SVG input file")
    if not os.path.isfile(INKSCAPE_BIN):
        raise ValueError("Can't find inkscape binary '" + INKSCAPE_BIN + "'")
    if not os.path.isfile(PATCH_BIN):
        raise ValueError("Can't find patching binary '" + PATCH_BIN + "'")

    filename = sys.argv[1]
    ask_page = None
    if len(sys.argv) == 3:
        ask_page = int(sys.argv[2])

    page_count = subprocess.run([INKSCAPE_BIN, "--query-pages", filename], capture_output=True, text=True).stderr.strip()

    print(f"Compiling '{filename}' into '{page_count}' pages of rendering code...\n")
    try:
        page_count = int(page_count)
    except:
        page_count = 1

    if page_count > 1:
        for p in range(page_count):
            if not ask_page or p == ask_page-1:
                print(f" * Page {p+1}")
                make_from_page(filename, p + 1)
    else:
        print(" * Single page SVG")
        make_from_page(filename)

def make_from_page(filename, page=0):

    args = []
    svgname = os.path.basename(filename)
    iname = svgname.rsplit(".", 1)[0].replace(" ", "_").replace("-", "_")
    if page:
        args += ["--pages="+str(page)]
        iname += "_" + str(page)
    name = "".join(bit.capitalize() for bit in iname.split("_"))
    content = subprocess.run([INKSCAPE_BIN]+args+[filename, "-o", OUTPUT_PNG], capture_output=True, text=True).stdout

    if not os.path.isfile(OUTPUT_PNG):
        raise ValueError("The PNG wasn't produced by inkscape. Did it fail to run correctly?")
    print(f"Compiling '{OUTPUT_PNG}' into result patch...\n")
    expected = subprocess.run([PATCH_BIN, OUTPUT_PNG], capture_output=True, text=True).stdout
    sname = iname.replace("_", "-")
    test_filename = os.path.join(SCRIPT_PATH, sname + ".cpp")
    expected_testname = "renderer-drawing-tests-" + sname

    print(f"Creating test '{test_filename}'...\n")
    with open(test_filename, "w") as fhl:
        fhl.write(f"""// SPDX-License-Identifier: GPL-2.0-or-later
//
// Generated by Inkscape from '{svgname}'

#include "../drawing-testbase.h"

{expected}

TEST_F(DrawingTest, {name})
{{
    Geom::IntPoint size = {{WIDTH, HEIGHT}};
    Geom::IntRect bounds = {{0, 0, WIDTH, HEIGHT}};
    Geom::Scale scale = {{1, 1}};

    auto surface = std::make_shared<Surface>(size, 1, rgb);
    auto context = std::make_unique<Context>(surface, bounds, scale);

{content}

    auto patch = surface->run_pixel_filter(PixelPatch{{
        ._method = PixelPatch::Method::COLORS,
        ._patch_x = 3,
        ._patch_y = 3,
    }});
    auto expected = PatchResult(EXPECTED, patch._stride);
    if (const char* png = std::getenv("MAKE_PNG")) {{
        if (patch != expected) {{
            surface->write_to_png(png);
        }}
    }}
    int delta = 0;
    std::ostringstream diff;
    for (unsigned c = 0; c < patch.size() || c < expected.size(); c++) {{
        if (c >= patch.size() || c >= expected.size() || patch[c] != expected[c]) {{
            delta++;
            diff << "X";
        }} else if (patch[c] == ' ') {{
            diff << " ";
        }} else {{
            diff << "-";
        }}  
    }}
    auto d = PatchResult(diff.str(), patch._stride);
    ASSERT_LT(delta, 10) << patch.pretty_print() << expected.pretty_print() << d.pretty_print();
}}
""")
    print(f"Attempting to build '{expected_testname}'...\n")
    if (not subprocess.call(["ninja", expected_testname])):
        print(f"Compile has been run, trying to run...\n")
        env = os.environ.copy()
        env["MAKE_PNG"] = FAIL_PNG
        if (subprocess.call([os.path.join(BIN_DIR, expected_testname)], env=env)):
            subprocess.call(["compare", "-metric", "RMSE", FAIL_PNG + "0.png", OUTPUT_PNG, DIFF_PNG])
            print(f"  -- Test failed, please compared '{OUTPUT_PNG}' to '{FAIL_PNG}' in '{DIFF_PNG}'")

if __name__ == "__main__":
    try:
        main()
    except ValueError as err:
        sys.stderr.write(str(err) + "\n")
        sys.exit(1)
