#!/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Author: Martin Owens
# Copyright: 2025
#
"""
Build test cases from svg files directly.
"""

import os
import sys
import subprocess

SCRIPT_PATH = os.path.dirname(os.path.realpath(__file__))
BIN_DIR = "./bin"
OUTPUTS = "./testfiles/renderer_output/"
INKSCAPE_BIN = os.path.join(BIN_DIR, "inkscape")
PATCH_BIN = os.path.join(BIN_DIR, "renderer-png-out")

def get_pages(filename):
    if not os.path.isfile(filename):
        sys.stderr.write(f"Can't find file: '{filename}'")
        sys.exit(1)
    parse = None
    with open(filename, 'r') as fhl:
        for line in fhl:
            if "<defs" in line:
                parse = ""
            if parse is not None:
                parse += line
            if "</defs>" in line:
                break
    if not parse:
        return

    parse = parse.replace("\n", "").replace(">", "\n").split("<view")

    labels = []
    for i, page in enumerate(parse[1:]):
        attrs = dict([tuple(a.replace("\"", "").strip().split("=", 1)) for a in page.split("\" ") if "=" in a]) 
        label = attrs.get("inkscape:label", attrs.get("label", f"badpage{i+1}")) 
        label = label.encode('ascii', 'replace').decode("ascii").lower()
        label = label.strip().replace(" ", "-").replace("_", "-").replace(";", "-")
        if label in labels or not label:
            label = f"badpage{i+1}"
        labels.append(label)
    if not labels:
        labels = ["page0"]
    return labels


def main():
    if len(sys.argv) < 2:
        raise ValueError("Please call with SVG input file")
    if not os.path.isfile(INKSCAPE_BIN):
        raise ValueError("Can't find inkscape binary '" + INKSCAPE_BIN + "'")
    if not os.path.isfile(PATCH_BIN):
        raise ValueError("Can't find patching binary '" + PATCH_BIN + "'")
    if not os.path.isdir(OUTPUTS):
        os.makedirs(OUTPUTS)

    filename = sys.argv[1]
    ask_page = None
    if len(sys.argv) == 3:
        ask_page = int(sys.argv[2])

    print(f"Compiling '{filename}' into rendering code...")
    pages = get_pages(filename)

    svgname = os.path.basename(filename)
    iname = svgname.rsplit(".", 1)[0].replace(" ", "_").replace("-", "_")
    test_suffix = iname.replace("_", "-")
    test_name = "renderer-drawing-tests-" + test_suffix

    with open(os.path.join(SCRIPT_PATH, test_suffix + ".cpp"), "w") as fhl:
        fhl.write(f"""// SPDX-License-Identifier: GPL-2.0-or-later
//
// Generated by Inkscape from '{svgname}'
// Command: {sys.argv[0]} "{filename}" {ask_page}
//

#include "../drawing-testbase.h"
""")
        for p in range(len(pages)):
            if not ask_page or p == ask_page-1:
                print(f"\nPage {p+1} '{pages[p]}'")
                fhl.write(make_from_page(filename, iname, p + 1, pages[p]))

    print(f" * Attempting to build '{test_name}'...")
    build_call = subprocess.run(["ninja", test_name], capture_output=True)
    if not build_call.returncode:
        print(f" * Compile has been run, trying to run...")
        run_call = subprocess.run([os.path.join(BIN_DIR, test_name)], capture_output=True)
        if not run_call.returncode:
            print(f" * Test passed")
        else:
            #diff_png = os.path.join(OUTPUTS, sname + "_diff.png")
            #subprocess.run(["compare", "-metric", "RMSE", fail_png + "0.png", output_png, diff_png], capture_output=True)
            print(f" ! Test failed")

        sys.stderr.write(run_call.stderr.decode("utf8"))
        sys.stdout.write(run_call.stdout.decode("utf8"))
    else:
        sys.stderr.write(build_call.stderr.decode("utf8"))
        sys.stdout.write(build_call.stdout.decode("utf8"))


def make_from_page(filename, iname, page=0, label=""):
    page_label = label.replace(" ", "_").replace("-", "_")
    test_label = "".join(bit.capitalize() for bit in page_label.split("_"))

    testcase_name = f"{iname}_{page_label}".replace("_", "-")
    output_png = os.path.join(OUTPUTS, testcase_name + "_reference.png")
    fail_png = os.path.join(OUTPUTS, testcase_name)

    env = os.environ.copy()
    env["IMAGE_PREFIX"] = os.path.join(SCRIPT_PATH, testcase_name + "_image")

    args = [INKSCAPE_BIN, "--pages="+str(page), filename, "-o", output_png]
    content = subprocess.run(args, capture_output=True, text=True, env=env).stdout

    if not os.path.isfile(output_png):
        raise ValueError("The PNG wasn't produced by inkscape. Did it fail to run correctly?")
    print(f" * Compiling '{output_png}' into result patch...")
    res = subprocess.run([PATCH_BIN, output_png], capture_output=True, text=True)
    if res.returncode:
        return f"// Error generating '{test_label}'\n/*{res.stderr}*/";
        
    expected = res.stdout.replace("\n;", ";").replace("\n", "\n    ")

    print(f" * Creating test '{test_label}'...")
    return f"""
TEST_F(DrawingTest, {test_label})
{{
    {expected}

    prepare_test({{width, height}});

{content}

    assert_drawing(expected, "{fail_png}", 20);
}}
"""

if __name__ == "__main__":
    try:
        main()
    except ValueError as err:
        sys.stderr.write(str(err) + "\n")
        sys.exit(1)
